@usernameBTP = {{$dotenv BTP-USER}}
@passwordBTP= {{$dotenv BTP-PASSWORD}}

@urlXSUAA = {{$dotenv HOST_XSUAA}}

####
# grant_type=password ou client_credentials para ambiente da sap exp
####

### login 
GET {{urlXSUAA}}/oauth/token
    ?grant_type=client_credentials
    &username={{usernameBTP}}
    &password={{passwordBTP}}
Content-Type: 'application/x-www-form-urlencoded'
Authorization: Basic {{$dotenv USER-XSUAA}}:{{$dotenv PASS-XSUAA}}