kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-data-pvc
  namespace: default
  labels:    
    app: postgres  
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi