apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: default  # Ajuste conforme necessário
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres  # Ajuste o selector conforme seu Deployment ou StatefulSet
