@baseUrl = http://localhost:3000
### Teste - Buscar clima padrão (sem parâmetros)
GET {{baseUrl}}/weather/current
Accept: application/json


### Teste - Buscar clima com latitude e longitude
GET {{baseUrl}}/weather/current?lat=46.9481&lon=7.4474
Accept: application/json
