@baseUrl = https://spro-examples-weather-api.cfa1d98.kyma.ondemand.com
@usernameBTP = {{$dotenv BTP-USER}}
@passwordBTP= {{$dotenv BTP-PASSWORD}}

### login 
# @name tokenPAYDEV
GET https://0ff873c4trial.authentication.us10.hana.ondemand.com/oauth/token
    ?grant_type=password
    &username={{usernameBTP}}
    &password={{passwordBTP}}
Content-Type: 'application/x-www-form-urlencoded'
Authorization: Basic {{$dotenv USER-XSUAA}}:{{$dotenv PASS-XSUAA}}

@token = {{tokenPAYDEV.response.body.access_token}}

GET {{baseUrl}}/weather/current
Accept: application/json
Authorization: Bearer {{token}}

### Teste - Buscar clima com latitude e longitude
GET {{baseUrl}}/weather/current?lat=46.9481&lon=7.4474
Accept: application/json
Authorization: Bearer {{token}}